### PR TITLE
Added support for IP2Location.io API

### PR DESCRIPTION
**Pull request by ip2location-com**

### CODE REVIEW

**Comment by tsosunchia** [comment]
https://github.com/nxtrace/NTrace-V1/issues/6#issuecomment-1705367714

如果你们的API，只能在填写token的情况下使用，请不要来倒垃圾了

**Comment by tsosunchia** [comment]
我正在考虑将你们的可耻行径挂在本项目的首页进行批判，我限你们24小时内解释可能存在的误会😅，否则我保留以任何方式回应你司对本项目灌水/骚扰行为的权利。

**Comment by ip2location-com** [comment]
As you mentioned we need to contribute instead

> 我正在考虑将你们的可耻行径挂在本项目的首页进行批判，我限你们24小时内解释可能存在的误会😅，否则我保留以任何方式回应你司对本项目灌水/骚扰行为的权利。

Based on the issues 6, you want us to contribute to open-source project instead of just aksing. We agreed and promised to provide PR and it is up to the team to decide if they want to merge or not.

Are we lost in the translation?

**Comment by tsosunchia** [comment]
https://github.com/nxtrace/NTrace-V1/issues/6#issuecomment-1705367714
截屏2023-09-30 09 10 35

我已经在此issue的这条回复中明确说了，其他Geoip提供商比如ipinfo.io , ip-api.com等“他们在不提供任何TOKEN时均能为用户提供使其满意的结果”，然而你们IP2Location若不使用token则无法获取结果。我还明确说了：“在彻底改变你们现在这该死的现状前，你们发一次这样的ISSUE我就喷一次。”

---------------------------------------------------
I have made it clear in this reply to this issue that other Geoip providers such as ipinfo.io, ip-api.com, etc. "When users try to use your API without providing a TOKEN, they're bound to be disappointed.", but your IP2Location If users don't use token, they can't get the result. I also made it clear: "Until you completely rectify this atrocious situation, every time you post an ISSUE of this nature, I'll call you out."

**Comment by ip2location-com** [comment]
I think your message was not clear. I have explained the reason why a registration is required at this moment and I thought your context was referred to no contribution to this project. We have mentioned we will work on it in our last reply and no one has objected it. Thus, we have took our time to work on a PR and you reacted negatively on it. Anyway, you have declined the PR and we are cool with it.

**Comment by tsosunchia** [comment]
还狡辩呢，我已经可以得出结论，对于此开源项目，IP2Location没有任何诚意，我们将禁止IP2Lacation今后以任何形式出现在本项目的开源社区内。
顺便一说，就IP2Location这种令人作呕的做法和态度，我想不难理解ipinfo.io为什么既受人尊敬又市场占有率高了😁

**Comment by tsosunchia** [comment]
你有一个小时的时间行使你的“最后陈述权”，到时间后，我们将在本org范围内全面封禁IP2Location这家令人作呕的公司。

**Pull request closed without merging**
