### PR TITLE
Enhance ipinfoLocal.mmdb file lookup

### PR DESCRIPTION
**Pull request by breakertt**
Both source code and documents are updated, however, I only tested on Linux environment.

### CODE REVIEW

**Comment by tsosunchia** [comment]
Good job  
但是为了统一环境变量的读取方式，
需要修改这部分代码
```golang
envIPInfoLocalPath := os.Getenv("NEXTTRACE_IPINFOLOCALPATH")
```
需要放在这个文件里`https://github.com/nxtrace/NTrace-V1/blob/main/util/util.go`  
并参考该文件中19行附近的代码  

非常感谢您的工作

**Comment by breakertt** [comment]
Thanks a lot for your quick reply, I have made the refactor you requested.

**Comment by tsosunchia** [comment]
`Searching for ipinfoLocal.mmdb in these folders: [/root/ /root/ /usr/local/share/nexttrace/ /usr/share/nexttrace/]`  
目前的默认行为是显示这条日志，是不是不显示更好一些呢？

**Comment by breakertt** [comment]
Sorry it is meant to be debug only, I should have removed it before committing.

**Comment by tsosunchia** [comment]
根据 ACTIONS 的自动检查，`ipgeo/ipinfoLocal.go` 中需要修改

> "fmt" imported and not used

**Comment by breakertt** [comment]
Sorry fixed

**Comment by tsosunchia** [comment]
well done

**Pull request merged**
